import { icons } from '@assets';

export const accounts_rows = [
  {
    name: 'John Doe',
    email: 'john.doe@example.com',
    workPhone: '(123) 456-7890',
    nextActivity: 'Follow-up Meeting',
    score: 85,
    tags: ['Lead', 'High Value'],
    salesOwner: 'Alice Johnson',
    salesStatus: 'Active',
  },
  {
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    workPhone: '(234) 567-8901',
    nextActivity: 'Initial Call',
    score: 78,
    tags: ['Prospect'],
    salesOwner: 'Bob Anderson',
    salesStatus: 'Active',
  },
  {
    name: 'Michael Brown',
    email: 'michael.brown@example.com',
    workPhone: '(345) 678-9012',
    nextActivity: 'Demo Scheduled',
    score: 90,
    tags: ['Lead', 'Demo'],
    salesOwner: 'Carol Thompson',
    salesStatus: 'Active',
  },
  {
    name: 'Emily Davis',
    email: 'emily.davis@example.com',
    workPhone: '(456) 789-0123',
    nextActivity: 'Proposal Sent',
    score: 65,
    tags: ['Lead'],
    salesOwner: 'Dave Wilson',
    salesStatus: 'Follow-up',
  },
  {
    name: 'Chris Johnson',
    email: 'chris.johnson@example.com',
    workPhone: '(567) 890-1234',
    nextActivity: 'Contract Review',
    score: 72,
    tags: ['High Value'],
    salesOwner: 'Eva Martinez',
    salesStatus: 'Active',
  },
  {
    name: 'Jessica Lee',
    email: 'jessica.lee@example.com',
    workPhone: '(678) 901-2345',
    nextActivity: 'Follow-up Call',
    score: 88,
    tags: ['Lead', 'Prospect'],
    salesOwner: 'Frank Harris',
    salesStatus: 'Inactive',
  },
  {
    name: 'David Smith',
    email: 'david.smith@example.com',
    workPhone: '(789) 012-3456',
    nextActivity: 'Product Demo',
    score: 80,
    tags: ['Prospect', 'High Value'],
    salesOwner: 'Grace Lee',
    salesStatus: 'Active',
  },
  {
    name: 'Laura Wilson',
    email: 'laura.wilson@example.com',
    workPhone: '(890) 123-4567',
    nextActivity: 'Negotiation',
    score: 77,
    tags: ['Lead', 'Prospect'],
    salesOwner: 'Henry Johnson',
    salesStatus: 'Follow-up',
  },
  {
    name: 'Peter Clark',
    email: 'peter.clark@example.com',
    workPhone: '(901) 234-5678',
    nextActivity: 'Final Review',
    score: 82,
    tags: ['High Value'],
    salesOwner: 'Isabel Green',
    salesStatus: 'Active',
  },
  {
    name: 'Nancy Taylor',
    email: 'nancy.taylor@example.com',
    workPhone: '(012) 345-6789',
    nextActivity: 'Check-in Call',
    score: 75,
    tags: ['Lead'],
    salesOwner: 'Jack White',
    salesStatus: 'Inactive',
  },
  {
    name: 'Steven Martin',
    email: 'steven.martin@example.com',
    workPhone: '(123) 456-7891',
    nextActivity: 'Follow-up Email',
    score: 83,
    tags: ['Prospect'],
    salesOwner: 'Karen Black',
    salesStatus: 'Active',
  },
  {
    name: 'Olivia Harris',
    email: 'olivia.harris@example.com',
    workPhone: '(234) 567-8902',
    nextActivity: 'Initial Meeting',
    score: 79,
    tags: ['Lead', 'High Value'],
    salesOwner: 'Larry King',
    salesStatus: 'Follow-up',
  },
  {
    name: 'Daniel Lewis',
    email: 'daniel.lewis@example.com',
    workPhone: '(345) 678-9013',
    nextActivity: 'Product Demo',
    score: 86,
    tags: ['Lead', 'Demo'],
    salesOwner: 'Megan Parker',
    salesStatus: 'Active',
  },
  {
    name: 'Sophia Allen',
    email: 'sophia.allen@example.com',
    workPhone: '(456) 789-0124',
    nextActivity: 'Contract Review',
    score: 81,
    tags: ['High Value', 'Prospect'],
    salesOwner: 'Nick Turner',
    salesStatus: 'Active',
  },
  {
    name: 'Andrew Young',
    email: 'andrew.young@example.com',
    workPhone: '(567) 890-1235',
    nextActivity: 'Proposal Sent',
    score: 74,
    tags: ['Lead'],
    salesOwner: 'Olivia Perez',
    salesStatus: 'Follow-up',
  },
  {
    name: 'Mia Scott',
    email: 'mia.scott@example.com',
    workPhone: '(678) 901-2346',
    nextActivity: 'Negotiation',
    score: 69,
    tags: ['Lead'],
    salesOwner: 'Paul Adams',
    salesStatus: 'Inactive',
  },
  {
    name: 'William Hill',
    email: 'william.hill@example.com',
    workPhone: '(789) 012-3457',
    nextActivity: 'Check-in Call',
    score: 76,
    tags: ['Prospect'],
    salesOwner: 'Quincy Mitchell',
    salesStatus: 'Active',
  },
  {
    name: 'Isabella Rivera',
    email: 'isabella.rivera@example.com',
    workPhone: '(890) 123-4568',
    nextActivity: 'Follow-up Meeting',
    score: 87,
    tags: ['Lead', 'High Value'],
    salesOwner: 'Rachel Cooper',
    salesStatus: 'Follow-up',
  },
  {
    name: 'James Baker',
    email: 'james.baker@example.com',
    workPhone: '(901) 234-5679',
    nextActivity: 'Initial Call',
    score: 84,
    tags: ['Prospect'],
    salesOwner: 'Samantha Torres',
    salesStatus: 'Active',
  },
  {
    name: 'Evelyn Brooks',
    email: 'evelyn.brooks@example.com',
    workPhone: '(012) 345-6790',
    nextActivity: 'Demo Scheduled',
    score: 73,
    tags: ['Lead', 'Demo'],
    salesOwner: 'Timothy Evans',
    salesStatus: 'Inactive',
  },
];
