import {
  IconBasket,
  IconBuildingStore,
  IconCategory2,
  IconStars,
  IconUsers,
  IconWallet,
} from '@tabler/icons-react';
import { hexToRgba } from './colors';

export const ss = {
  auth_mode: 'auth_mode',
  sidebar: 'sidebar',
  userData: 'userData',
  admin: 'admin',
  token: 'token',
  toast: 'toast',
};

export const modal = {
  filterDrawer: 'filterDrawer',
  inviteModal: 'inviteModal',
  paymentModal: 'paymentModal',
  registerModal: 'registerModal',
  leadModalForm: 'leadModalForm',
  eventModalForm: 'eventModalForm',
  orderModal: 'orderModal',
  callModal: 'callModal',
  editModal: 'editModal',
  complainModal: 'complainModal',
  confirmMatchMaker: 'confirmMatchMaker',
  consultationModal: 'consultationModal',
  builderModal: 'builderModal',
};

export const colors = {
  primary: '#5812cb',
  primary_lightest: '#f0f3f9',
  primary_lighter: '#d9e0ec',
  primary_light: '#afb8c4',
  primary_darker: '#2e086d',
  primary_darkest: '#14032f',
  primary_dark: '#40099b',
  primary_border: '#d9e0ec',
  secondary: '#ff5500',
  secondary_lightest: '#fff4ea',
  secondary_lighter: '#f0e2d5',
  secondary_light: '#e4d1bf',
  body: '#070112',
  white: '#ffffff',
  body_light: '#7e7391',
  success: '#00bc56',
  error: '#d50040',
  // Lead
  NEW: '#1E90FF',
  CONTACTED: '#00BFFF',
  INTERESTED: '#32CD32',
  QUALIFIED: '#FFD700',
  PROPOSAL_SENT: '#FF8C00',
  NEGOTIATION: '#FF4500',
  CLOSED_WON: '#6A5ACD',
  CLOSED_LOST: '#DC143C',
  UNQUALIFIED: '#A9A9A9',
  FOLLOW_UP: '#20B2AA',
  IN_PROGRESS: '#4682B4',
  REOPENED: '#8A2BE2',
  NOT_INTERESTED: '#FF6347',
  DUPLICATE: '#808080',
  todo: '#536cd2',
  in_progress: '#FFD700',
  done: '#32CD32',
  blocked: '#FF6347',
  on_hold: '#FFA500',
  canceled: '#A9A9A9',
  online: '#5812cb',
  offline: '#ff5500',
  indigo: '#4B0082',
  steelBlue: '#4682B4',
  slateBlue: '#6A5ACD',
  seaGreen: '#2E8B57',
  tomato: '#FF6347',
  saddleBrown: '#8B4513',
  chocolate: '#D2691E',
  lightSeaGreen: '#20B2AA',
  slateGray: '#708090',
  indianRed: '#CD5C5C',
  goldenrod: '#DAA520',
  cadetBlue: '#5F9EA0',
  sienna: '#A0522D',
  darkGoldenrod: '#B8860B',
  darkSeaGreen: '#8FBC8F',
  mediumPurple: '#9370DB',
};

export const main_navigation: any = [
  {
    title: 'Manage',
    title2: 'Vendors',
    color_light: hexToRgba('#1edbf3', 0.15),
    icon: <IconBuildingStore className={'primary_darker'} />,
  },
  {
    title: 'Manage',
    title2: 'Customers',
    color_light: hexToRgba('#1edbf3', 0.15),
    icon: <IconUsers className={'primary_darker'} />,
  },
  {
    title: 'Manage',
    title2: 'Order',
    color_light: hexToRgba('#1edbf3', 0.15),
    icon: <IconBasket className={'primary_darker'} />,
  },
  {
    title: 'Manage',
    title2: 'Transactions',
    color_light: hexToRgba('#1edbf3', 0.15),
    icon: <IconWallet className={'primary_darker'} />,
  },

  {
    title: 'Manage',
    title2: 'Menus',
    color_light: hexToRgba('#1edbf3', 0.15),
    icon: <IconCategory2 className={'primary_darker'} />,
  },
  {
    title: 'Manage',
    title2: 'Reviews',
    color_light: hexToRgba('#1edbf3', 0.15),
    icon: <IconStars className={'primary_darker'} />,
  },
];

export const profile_status: any = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
};
